import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '../components/Nav'
import { Header } from '../components/Header'

const inter = Inter({ subsets: ['latin'] })
 
const metadata: Metadata = {
  title: 'Portifolio',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Nav />
        <main>{children}</main>
      </body>
    </html>
  )
}
